# Generated by Django 4.2.4 on 2023-08-21 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('selector', models.CharField(max_length=200)),
                ('checkTime', models.DateTimeField(default=datetime.datetime(2023, 8, 21, 15, 28, 8, 999646))),
            ],
        ),
    ]
