# Generated by Django 4.2.4 on 2023-08-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_alter_ranksite_checktime'),
    ]

    operations = [
        migrations.RunSQL(
            sql = migrations.RunSQL.noop,
            reverse_sql = migrations.RunSQL.noop,
            state_operations = [
                migrations.RemoveField(
                    model_name = "ranksite",
                    name = "checkTime"
                ),
            ],
        ),
    ]
